# Travis-CI configuration file for SuperTux
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
# Heavily borrowed from SuperTuxKart's travis.yml.
#
# SuperTuxKart's travis.yml file can be found here:
# https://github.com/supertuxkart/stk-code/blob/master/.travis.yml
# License: https://github.com/supertuxkart/stk-code/blob/master/COPYING
#

language: cpp
dist: trusty
sudo: required

compiler:
  - gcc

matrix:
  fast_finish: true

os:
  - linux

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    - secure: "eVEyzIVjDlB16EPkXmj74tyF9pgX34kpgvBUMXJJ+hduuPwaGC6vl8T164fNQUIua2Z2/PqxmTLJRR3n5Bbkdf859NdX+4JUzc3SoFEKlgcLMYnOQeuimUAiMKxe4vmC4sub5LZVFsp9ORzVYkXgiMBnxiD5GuYxvZPy1lCaH9E="
    # BINTRAY_KEY env var
    - secure: "E++FmjzZZrvkJpUHZajLUaO1wd0QHcyVidVx8qVeGUJm/khCPBJuhkSe6R2BphcBeeAuhVlsXo26SWCAn89r2KT2OHB/lwtK2CWhO5vOl5bI5o4nFc+m55e2gDIebSBrXQPITEQJpQx1zBL4FVw/A2xQRl+IcjF/EiIzG8Znslc="
    - GLBINDING_VERSION=2.1.1
  matrix:
    - BUILD_TYPE="Debug"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update;
        brew upgrade cmake;
        brew install libogg libvorbis glew openal-soft sdl2 sdl2_image;
    fi
  # Try building with GLBinding
  # Note: glbindings ./configure needs to be run twice in order to generate a makefile
  - if [ "$USE_GLBINDING" = "ON" ]; then
        wget https://github.com/cginternals/glbinding/archive/v$GLBINDING_VERSION.tar.gz -O - | tar xz;
        cd glbinding-$GLBINDING_VERSION && ./configure --prefix=/usr && ./configure --prefix=/usr;
        cd build && make -j3 && sudo make install;
        cd ../..;
    fi
  # Fetch the entire git history
  - git fetch --unshallow

script:
  - mkdir "build-$BUILD_TYPE"
  - cd "build-$BUILD_TYPE"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON -DGLBINDING_ENABLED=$USE_GLBINDING -DBUILD_TESTS=ON
  - make -j3
  - make install DESTDIR="/tmp/supertux-$BUILD_TYPE"
  - ./test_supertux2

after_success:
  - ../.travis/package.sh

deploy:
  - provider: script
    script: ../.travis/deploy.sh
    skip_cleanup: true
    on:
      branch: master
      condition: $BUILD_TYPE = Release
  - provider: releases
    api_key:
      secure: oOoWGIvtMne9b413EGv3GSaV8PE/X1P3e85hIdTvRdxs5VTWHi9eeWpEknru8N8hQ+iIkvD2QpUvwL6Qgf7myP3OwXWEf7o6+Qxjfl49oJaROTeVUR7uzOYTmYYTCZG0b3jQKYu5JkVqJzwTNmT0GturHkW5pzsAy/rHUDuLfkI=
    file: "SuperTux-*"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      condition: $BUILD_TYPE = Release

addons:
  apt:
    packages:
    - cmake
    - build-essential
    - libc++-dev
    - libogg-dev
    - libvorbis-dev
    - libglew-dev
    - libopenal-dev
    - libboost-all-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - rpm
    - sshpass
  coverity_scan:
    project:
      name: "SuperTux/supertux"
      description: "Build submitted via Travis CI"
    notification_email: supertux-commit@lists.lethargik.org
    build_command_prepend: "cmake . && make clean"
    build_command:   "make -j 3"
    branch_pattern: coverity_scan

notifications:
  email:
    - supertux-commit@lists.lethargik.org
  slack:
    secure: cH9u9+EfaPGIcmIcy06hxp5coMmBSKorgABXwE5M06hWbwL+4SIaAlOf9QhrOPi7TZKyyI5GXh687pWNtrgUzaBFhNrPOa/tIzr6kJryAkoFBRdn0sOsf/xYyDgTUfzS79HLYxdv7KDckmiPcgTxGGJOJ3797HBeKaEeufefzlU=
