# Travis-CI configuration file for SuperTux
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
# Heavily borrowed from SuperTuxKart's travis.yml.
#
# SuperTuxKart's travis.yml file can be found here:
# https://github.com/supertuxkart/stk-code/blob/master/.travis.yml
# License: https://github.com/supertuxkart/stk-code/blob/master/COPYING
#

language: cpp
dist: trusty
sudo: required

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true
  exclude:
  - compiler: gcc
    os: osx
  include:

os:
  - linux
  - osx

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    - secure: "eVEyzIVjDlB16EPkXmj74tyF9pgX34kpgvBUMXJJ+hduuPwaGC6vl8T164fNQUIua2Z2/PqxmTLJRR3n5Bbkdf859NdX+4JUzc3SoFEKlgcLMYnOQeuimUAiMKxe4vmC4sub5LZVFsp9ORzVYkXgiMBnxiD5GuYxvZPy1lCaH9E="
    # BINTRAY_KEY env var
    - secure: "E++FmjzZZrvkJpUHZajLUaO1wd0QHcyVidVx8qVeGUJm/khCPBJuhkSe6R2BphcBeeAuhVlsXo26SWCAn89r2KT2OHB/lwtK2CWhO5vOl5bI5o4nFc+m55e2gDIebSBrXQPITEQJpQx1zBL4FVw/A2xQRl+IcjF/EiIzG8Znslc="
    # DOWNLOAD_APIKEY env var
    - secure: "ZfRyz4HyLtCtHSrCzB+VwdRP3QLbhcXiqsUAhBYNBz6fU8B4l7UchcRrTVsSQJMJeQQ3V7baJsqi4vAcxtd2aV/UDb82aWy9+lwexecjS+fVNh6Ace8j69PVeywpVVonY2Mk/8LeEAvBkjB1OeRlE+gMC08QwOiHqkR2qVcwNYA="
    # TRANSIFEX_TOKEN env var
    - secure: "K76kd28Ub2wQ58XIk/ARrEPtgdlXqdkTKp2yUHAkxGQccRLe64yelFrBCh74AUJ4UUaYdRqq/s/ArPLh9tzfgSOjEwmUeY9EFMoicIAYAb/bt721utXBFast3p+cDbrlT1I9nOsyiAItX/uMad4Q0kDVDGXk13nDnxrPM5hxJOE="
    - GLBINDING_VERSION=2.1.3
  matrix:
    - BUILD_TYPE="Debug"
    - BUILD_TYPE="Release"
    - USE_GLBINDING=ON

before_install:
  # Possibly should not generate packages for all builds?
  - export PACKAGE="ON";
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CC" = "gcc" ] && [ "$BUILD_TYPE" = "Release" ]; then
      export RELEASE="ON";
    fi;
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$BUILD_TYPE" = "Release" ]; then
      export RELEASE="ON";
    fi;
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew upgrade cmake;
      brew install bash libogg libvorbis glew openal-soft sdl2 sdl2_image;
    fi
  # Try building with GLBinding
  # Note: glbindings ./configure needs to be run twice in order to generate a makefile
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$USE_GLBINDING" = "ON" ]; then
      wget https://github.com/cginternals/glbinding/archive/v$GLBINDING_VERSION.tar.gz -O - | tar xz;
      cd glbinding-$GLBINDING_VERSION && ./configure --prefix=/usr && ./configure --prefix=/usr;
      cd build && make -j3 && sudo make install;
      cd ../..;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$USE_GLBINDING" = "ON" ]; then
      brew install glbinding;
    fi
  # Fetch the entire git history
  - git fetch --unshallow

  # Install transifex client:
  - if [ "$RELEASE" = "ON" ] && [ ! "$USE_GLBINDING" = "ON" ]; then
      sudo easy_install pip;
      sudo pip install --upgrade urllib3;
      sudo pip install transifex-client;
    fi

script:
    # Update translation templates (only once per commit)
  - if [ "$RELEASE" = "ON" ] && [ ! "$USE_GLBINDING" = "ON" ]; then
      ./makepot.sh;
      tx init --token=${TRANSIFEX_TOKEN} --force --no-interactive --skipsetup;
      tx push -s;
    fi
  - mkdir "build-$BUILD_TYPE"
  - cd "build-$BUILD_TYPE"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON -DGLBINDING_ENABLED=$USE_GLBINDING -DBUILD_TESTS=ON -DCMAKE_INSTALL_MESSAGE=NEVER -DCMAKE_INSTALL_PREFIX=/usr -DINSTALL_SUBDIR_BIN=bin -DINSTALL_SUBDIR_SHARE=share/supertux2
  - make -j3
  - make install DESTDIR="/tmp/supertux-$BUILD_TYPE"
  - ./test_supertux2

after_success:
  - ../.travis/package.sh

deploy:
  - provider: script
    script: ../.travis/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
      condition: $RELEASE = ON
  - provider: releases
    api_key:
      secure: oOoWGIvtMne9b413EGv3GSaV8PE/X1P3e85hIdTvRdxs5VTWHi9eeWpEknru8N8hQ+iIkvD2QpUvwL6Qgf7myP3OwXWEf7o6+Qxjfl49oJaROTeVUR7uzOYTmYYTCZG0b3jQKYu5JkVqJzwTNmT0GturHkW5pzsAy/rHUDuLfkI=
    file: "SuperTux*"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      condition: $RELEASE = ON

addons:
  apt:
    packages:
    - cmake
    - build-essential
    - libc++-dev
    - libogg-dev
    - libvorbis-dev
    - libglew-dev
    - libopenal-dev
    - libboost-all-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - python3
    - rpm
    - sshpass
  coverity_scan:
    project:
      name: "SuperTux/supertux"
      description: "Build submitted via Travis CI"
    notification_email: supertux-commit@lists.lethargik.org
    build_command_prepend: "cmake . && make clean"
    build_command:   "make -j 3"
    branch_pattern: coverity_scan

notifications:
  email:
    - supertux-commit@lists.lethargik.org
  slack:
    secure: cH9u9+EfaPGIcmIcy06hxp5coMmBSKorgABXwE5M06hWbwL+4SIaAlOf9QhrOPi7TZKyyI5GXh687pWNtrgUzaBFhNrPOa/tIzr6kJryAkoFBRdn0sOsf/xYyDgTUfzS79HLYxdv7KDckmiPcgTxGGJOJ3797HBeKaEeufefzlU=
